entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"     # ✅ Très important

api:
  dashboard: true        # ✅ PAS 'insecure: true' ici

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml   # ✅ pour charger la config dynamique

certificatesResolvers:
  le:
    acme:
      email: scarface@my-siem.lab
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web


