entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"     

api:
  dashboard: true        

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml   

certificatesResolvers:
  le:
    acme:
      email: scarface@my-siem.lab
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web


